# version: "3.9" 
services:
  metabase-frontend:
    build:
      context: ./metabase-frontend  
      dockerfile: Dockerfile
    image: metabase-frontend:latest
    container_name: metabase-frontend
    hostname: metabase-frontend
    ports:
      - "3000:3000"
    networks:
      - metanet1
    restart: always
    depends_on:
      - metabase-backend
        
  metabase-backend:
    build:
      context: ./metabase-backend  
      dockerfile: Dockerfile
    image: metabase-backend:latest
    container_name: metabase-backend
    hostname: metabase-backend
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "3002:3002"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: postgres
      MB_JETTY_PORT: 3002
      MB_SITE_URL: http://metabase.mynancy.io.vn:3000
    networks:
      - metanet1
    restart: always
    depends_on:
      - postgres
        
  postgres:
    image: postgres:latest
    container_name: postgres-metabase
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metanet1
    restart: always
      
  backend-bot:
    build:
      context: ./backend-bot
      dockerfile: Dockerfile
    image: backend-bot:latest
    container_name: backend-bot
    hostname: backend-bot
    ports:
      - "3001:3001"
    networks:
      - metanet1
    restart: always

volumes:
  postgres_data:  # Add persistent volume for database

networks:
  metanet1:
    driver: bridge
