version: "3.9"
services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres-metabase
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1
    restart: always
  backend-bot:
    build:
      context: ./backend-bot
      dockerfile: Dockerfile
    container_name: backend-bot
    hostname: backend-bot
    ports:
      - "3001:3001"
    networks:
      - metanet1
    restart: always
networks:
  metanet1:
    driver: bridge